import asyncio
import os
import subprocess
import time
import httpx
import sys
import sqlite3
from gaura_platform.mobile_stub.node import MobileNode
from gaura_platform.config.schema import BotInstanceConfig
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))

async def run_hub():
    """Starts the Central Hub in a separate process"""
    print("🚀 Starting Central Hub on port 8200...")
    return subprocess.Popen([sys.executable, "gaura_platform/central_hub/hub.py"])

async def run_mobile_app():
    """Starts the Mobile App UI Service"""
    print("📱 Starting Mobile App UI on http://localhost:8500...")
    env = os.environ.copy()
    env["NODE_ID"] = "phone_organic"
    return subprocess.Popen([sys.executable, "gaura_platform/mobile_app/app_server.py"], env=env)

async def setup_demo_nodes():
    """Simulates two users (phones) joining the network"""
    gemini_key = os.getenv("GEMINI_API_KEY", "MOCK_KEY")
    
    # 1. Register or Login Mock Users in Hub with UPI IDs
    async with httpx.AsyncClient() as client:
        for user_data in [
            {"email": "organic@gaura.ai", "password": "pass", "name": "Organic Farm", "role": "vendor", "upi_id": "organic@upi"},
            {"email": "tech@gaura.ai", "password": "pass", "name": "Tech Store", "role": "vendor", "upi_id": "tech@upi"}
        ]:
            res = await client.post("http://localhost:8200/signup", json=user_data)
            if res.status_code != 200:
                print(f"ℹ️ User {user_data['email']} might already exist. Attempting login...")
                await client.post("http://localhost:8200/login", json={"email": user_data['email'], "password": user_data['password']})

    # Node 1: Organic Seller
    node1 = MobileNode("phone_organic", "phone_organic_vault.db", gemini_key)
    # Node 2: Tech Seller
    node2 = MobileNode("phone_tech", "phone_tech_vault.db", gemini_key)
    
    async with httpx.AsyncClient() as client:
        # Link their nodes (In real app, this happens on login)
        # We need the user_ids which are UUIDs. For demo, we'll just link directly to node_ids for simplicity in search.
        # Modified search in Hub looks up users by node_id to get UPI.
        
        await client.post("http://localhost:8200/register_node", params={"node_id": "phone_organic", "callback_url": "http://localhost:9001"})
        await client.post("http://localhost:8200/register_node", params={"node_id": "phone_tech", "callback_url": "http://localhost:9002"})
        
        # Manually Update node_id in users table for demo
        conn = sqlite3.connect("hub_registry.db")
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET node_id = 'phone_organic' WHERE email = 'organic@gaura.ai'")
        cursor.execute("UPDATE users SET node_id = 'phone_tech' WHERE email = 'tech@gaura.ai'")
        conn.commit()
        conn.close()

        # Populate with some AI-Compute data
        print("📲 Node 1 (Organic): Processing fake upload for 'Almond Milk'...")
        p1 = await node1.process_seller_upload("Premium Almond Milk", "Grocery", 5.95, "YmFzZTY0X2Zha2VfaW1hZ2U=")
        
        print("📲 Node 2 (Tech): Processing fake upload for 'Gaura Pro Lens'...")
        p2 = await node2.process_seller_upload("Gaura Pro Lens", "Electronics", 299.00, "YmFzZTY0X2Zha2VfaW1hZ2U=")
        
        # Publish metadata to hub for search using the actual IDs generated by node
        await client.post("http://localhost:8200/publish_metadata", json={
            "id": p1['id'], "vendor_id": "phone_organic", "node_id": "phone_organic", 
            "name": p1['name'], "category": p1['category'], "base_price": p1['base_price']
        })
        await client.post("http://localhost:8200/publish_metadata", json={
            "id": p2['id'], "vendor_id": "phone_tech", "node_id": "phone_tech", 
            "name": p2['name'], "category": p2['category'], "base_price": p2['base_price']
        })

async def run_node_service(node_id: str, port: int):
    """Starts a Mobile Node Service in a separate process"""
    print(f"📲 Starting Node Service {node_id} on port {port}...")
    env = os.environ.copy()
    env["NODE_ID"] = node_id
    env["NODE_PORT"] = str(port)
    return subprocess.Popen([sys.executable, "gaura_platform/mobile_stub/node_service.py"], env=env)

async def run_bot_factory():
    """Starts the Bot Factory Service"""
    print("🤖 Starting Bot Factory on port 8400...")
    return subprocess.Popen([sys.executable, "gaura_platform/gaura_bot/factory.py"])

async def main():
    # 1. Start Hub
    hub_proc = await run_hub()
    time.sleep(3) 
    
    # 2. Start Bot Factory
    bot_proc = await run_bot_factory()
    time.sleep(2)

    # 3. Start Node Services for Demo
    node1_proc = await run_node_service("phone_organic", 9001)
    node2_proc = await run_node_service("phone_tech", 9002)
    time.sleep(2)

    # 4. Start Mobile App UI (The "Seller's App")
    app_proc = await run_mobile_app()
    time.sleep(2)
    
    try:
        # 5. Simulate Demo Nodes (Register & Upload)
        await setup_demo_nodes()
        print("\n✨ GAURA ECOSYSTEM LIVE!")
        print("🌍 Central Hub: http://localhost:8200")
        print("🤖 Bot Factory: http://localhost:8400")
        print("📱 Mobile App UI: http://localhost:8500")
        print("📡 Node 1: Port 9001 | Node 2: Port 9002")
        
        # Keep main loop alive
        while True:
            await asyncio.sleep(1)
            
    except KeyboardInterrupt:
        print("\nStopping ecosystem...")
        hub_proc.terminate()
        bot_proc.terminate()
        node1_proc.terminate()
        node2_proc.terminate()
        app_proc.terminate()

if __name__ == "__main__":
    asyncio.run(main())
